- hosts: httpd
  name: "Installing Docker"
  tasks:
  - package:
      name: "{{ item }}"
    vars:
      items:
      - docker-selinux
      - docker-engine
      state: present
    when:  ansible_os_family == "Debian"
  - package:
      name: "{{ item }}"
    vars:
      items:
      - docker-selinux
      - docker-engine
      state: present
    when:  ansible_os_family == "RedHat"
  - service:
       name: docker
       state: started
       enabled: yes
    when:  ansible_os_family == "Debian"
  - service:
       name: docker
       state: started
       enabled: yes
    when:  ansible_os_family == "Debian"

   